name: gift-registry

services:
  
  postgres: 
    container_name: gift-registry-postgres
    image: postgres:17.2
    pull_policy: missing
    ports: 
      - 5432:5432
    volumes:
      - ${POSTGRES_DATA}:/var/lib/postgresql/data/ 
      - ./postgres_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${DB_USER} -d ${DB_NAME}'"]
      interval: 10s
      timeout: 3s
      retries: 3
    environment:
      # Set up your DB credentials in environment variables
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    networks:
      - gift-registry-network

  app: 
    container_name: gift-registry-app
    image: gift-registry
    pull_policy: missing
    depends_on: 
      postgres:
          condition: service_healthy
    ports: 
      - "8080:8080" 
    environment:
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      EMAIL_FROM: ${EMAIL_FROM}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PASS: ${EMAIL_PASS}
      EMAIL_PORT: ${EMAIL_PORT}
      MIGRATIONS_DIR: "migrations"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://gift-registry-collector:4318 
      OTEL_METRIC_EXPORT_INTERVAL: "5000" # so we don't have to wait 60s for metrics
      STATIC_FILES_DIR: "."
      PORT: ${PORT}
      TEMPLATES_DIR: "templates"
    networks:
      - gift-registry-network

networks:
  gift-registry-network:
